version: '3'
services:
  rabbitmq:
    image: "rabbitmq:management"
    hostname: "rabbit"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    volumes:
      - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config
  producer:
    image: producer:1
    build:
      context: ./spring-boot-amqp-rabbitmq-producer
      dockerfile: Dockerfile
    volumes:
      - /data/producer
    ports:
      - "4444:4444"
    depends_on:
      - rabbitmq
  consumer:
    image: consumer:1
    build:
      context: ./spring-boot-amqp-rabbitmq-consumer
      dockerfile: Dockerfile
    volumes:
      - /data/consumer
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq
    
